#!/bin/bash

export ANSI_BREAK ANSI_NORMAL ANSI_UNDERLINE ANSI_FLASH ANSI_REVERSE
# Control characters
ANSI_BREAK=$'\X1B[0;01M'   # line break?
ANSI_NORMAL=$'\X1B[0;0M'   # clear color(s)
ANSI_UNDERLINE=$'\X1B[4M'  # underline
ANSI_FLASH=$'\X1B[5M'      # flash
ANSI_REVERSE=$'\X1B[7M'    # reverse video

# Normal color
export ANSI_NORMAL_BLACK ANSI_NORMAL_RED ANSI_NORMAL_GREEN ANSI_NORMAL_YELLOW
export ANSI_NORMAL_MAGENTA ANSI_NORMAL_CYAN ANSI_NORMAL_WHITE ANSI_NORMAL_BLUE
ANSI_NORMAL_BLACK=$'\X1B[0;30M'
ANSI_NORMAL_RED=$'\X1B[0;31M'
ANSI_NORMAL_GREEN=$'\X1B[0;32M'
ANSI_NORMAL_YELLOW=$'\X1B[0;33M'
ANSI_NORMAL_BLUE=$'\X1B[0;34M'
ANSI_NORMAL_MAGENTA=$'\X1B[0;35M'
ANSI_NORMAL_CYAN=$'\X1B[0;36M'
ANSI_NORMAL_WHITE=$'\X1B[0;37M'

# Bright color
export ANSI_BRIGHT_BLACK ANSI_BRIGHT_RED ANSI_BRIGHT_GREEN ANSI_BRIGHT_YELLOW
export ANSI_BRIGHT_BLUE ANSI_BRIGHT_MAGENTA ANSI_BRIGHT_CYAN ANSI_BRIGHT_WHITE
ANSI_BRIGHT_BLACK=$'\X1B[1;30M'
ANSI_BRIGHT_RED=$'\X1B[1;31M'
ANSI_BRIGHT_GREEN=$'\X1B[1;32M'
ANSI_BRIGHT_YELLOW=$'\X1B[1;33M'
ANSI_BRIGHT_BLUE=$'\X1B[1;34M'
ANSI_BRIGHT_MAGENTA=$'\X1B[1;35M'
ANSI_BRIGHT_CYAN=$'\X1B[1;36M'
ANSI_BRIGHT_WHITE=$'\X1B[1;37M'

# Background colors
export ANSI_BG_BLACK ANSI_BG_RED ANSI_BG_GREEN ANSI_BG_YELLOW
export ANSI_BG_BLUE ANSI_BG_MAGENTA ANSI_BG_CYAN ANSI_BG_WHITE
ANSI_BG_BLACK=$'\X1B[40M'
ANSI_BG_RED=$'\X1B[41M'
ANSI_BG_GREEN=$'\X1B[42M'
ANSI_BG_YELLOW=$'\X1B[43M'
ANSI_BG_BLUE=$'\X1B[44M'
ANSI_BG_MAGENTA=$'\X1B[45M'
ANSI_BG_CYAN=$'\X1B[46M'
ANSI_BG_WHITE=$'\X1B[47M'

function ansi_reset() {
    echo -ne "${ANSI_NORMAL}"
}

function ansi_bright_yellow() {
    echo -ne "${ANSI_BRIGHT_YELLOW}${*}${ANSI_NORMAL}"
}

function ansi_bright_red() {
    echo -ne "${ANSI_BRIGHT_RED}${*}${ANSI_NORMAL}"
}

function ansi_bright_green() {
    echo -ne "${ANSI_BRIGHT_GREEN}${*}${ANSI_NORMAL}"
}

function ansi_bright_white() {
    echo -ne "${ANSI_BRIGHT_WHITE}${*}${ANSI_NORMAL}"
}

function ansi_underline() {
    echo -ne "${ANSI_UNDERLINE}${*}${ANSI_NORMAL}"
}