#!/bin/sh

set -e 

for name in /usr/local/bin/last-*; do
    if [ ! -L ${name} ]; then
        continue
    fi

    target=$(readlink -f ${name})
    case "${target}" in
        /usr/local/share/last-tool/bin/last*)
            echo removing ${name} ... >> /tmp/prerm.log
            /bin/rm -f ${name}
            ;;
    esac
done
    
